# Generated by Django 5.0.7 on 2024-07-27 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=10)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='post_videos/%Y/%m/%d')),
                ('video_size_limit', models.PositiveIntegerField(default=10485760)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_entered', models.DateTimeField(auto_now=True)),
                ('profile_image', models.ImageField(default='profile_images/default.png', upload_to='profile_images/%Y/%m/%d', verbose_name='Profile Image')),
                ('bio', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=100)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='main.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
